Datatype convertion
NKcqx/CLIC pull request #140
Opened 2020-11-05 03:55 UTC by DLUTLiuFengyi

1. 实现了JavaRDD与Dataset之间的相互转换（Dataset是DataFrame的改进）
2. 将SQL操作包括对table的读写嵌入到Demo.java中
3. 将Spark SQL平台并入Spark平台中

2020-11-05 04:01 UTC, DLUTLiuFengyi commented
单元测试QueryOperatorTest.java在本地mvn pakage通过，但在线上没通过，原因是SparkContext在jvm中不能有两个以上，这个问题按理来说之前通过访问静态变量的方式能保证SparkContext只为一个，在本地运行和mvn打包没问题，但现在在线上却过不了。
要改其实应该不难，普通Spark算子用的是SparkContext，SQL算子用的是SparkSession，可以让普通Spark算子的SparkContext由SparkSession生成。

2020-11-05 04:29 UTC, NKcqx commented on executable-operator/executable-spark/src/main/java/fdu/daslab/executable/spark/operators/TableSource.java
> +        String tableName = "";
`tableName`的查找不依赖于文件有没有后缀名

2020-11-05 04:33 UTC, NKcqx commented on executable-operator/executable-spark/src/main/java/fdu/daslab/executable/spark/operators/TableToRDDOperator.java
> +                    String[] items = lineStr.split(separator);
这里的分隔符不是取决于用户，是系统定死的

2020-11-05 04:41 UTC, NKcqx commented on framework/src/main/resources/Operator/RDDToTable/conf/RDDToTableOperator.xml
> +        <parameter name="separator" data_type="string" default=","> </parameter>
是不是就不需要 `separator`了？

2020-11-05 04:42 UTC, NKcqx commented on framework/src/main/resources/Operator/TableToRDD/conf/TableToRDDOperator.xml
> +        <parameter name="separator" data_type="string" default=","> </parameter>
这个是不是也不需要了

2020-11-05 04:52 UTC, NKcqx commented on executable-operator/executable-basic/src/main/java/fdu/daslab/executable/udf/TestConvertFunc.java
> +    public StructType rddToTableFunc() {
`StructType`不能和实际的计算平台绑定

2020-11-05 04:52 UTC, NKcqx requested changes
整体写的非常好👍

2020-11-05 13:12 UTC, DLUTLiuFengyi commented
使用joinery库来提供java平台的DataFrame，但线上测试显示中心仓库(https://repo.maven.apache.org/maven2)没有这个库，因此需要找其他方法来实现java的DataFrame，实在不行自己手动实现一个（拉跨）

2020-11-08 10:19 UTC, NKcqx approved these changes
棒

2020-11-08 10:19 UTC, merged